
jwt:
  access_token_secret: G/0ZGXcM5wf3oNcVzHocbpI2O8xPYqzRHjHLl0U/luw=--WAGSsD92zttKmD2Q0TZwag==
  refresh_token_secret: ATsXKJK7r8t0T+RlqM9ZU2ehLsxzv+jDOS9aM6h1i7Q=--HAbNAv9yVaVbxJM7rDBpOA==

swagger:
  username: wJX10ghDUxIPIbGO2taE6l/yH7nyuKQnBSIaVlMDZL0=--eKVTvN4Ra3WgG+Nw089R/g==
  password: Md7Ja2L1uIReWCLm+Re823eq15jkQkWPV4KDfyP5G34=--LHs033X8zyfj5xG12BI6Vw==

database:
  name: xhBqKn3dhVr0eKE2dbV+bQgolJI0eVTCm2PhPRcwGwk=--yxgl6U1S4ZsfP7clgbqcRg==
  host: POFwwKIjRCvoXqI/PjQBog==--BSTtX2SGtIWhedbuGSbuMg==
  username: XIIPBAFSu1j+EDAGk4+bAA==--K0Jdn2owtB6yMAjB2bOibg==
  password: SqHUQ7M2Zwcl/W9oPdSqEw==--HYDze3nwqB+tLjz2VJxtqw==
  port: i0G3Lyprfq44CFbbpCpw9g==--ZkATAKgCtpayBfT15sGeDg==

emailLogin:
  tables: 8Yl64AEzZ8HyDwJGCHCklw==--u+omjh2Zr8ip++yCv1g3UA==
  passwordMinLength: l+FlTlvOWsuFNi6fb34L8w==--g8II0Y1ljx6DzUTbfAnLkw==
  rememberFor: y1rxsRurXj8A3W/42dG+lg==--HGAcl8CnG6jbZe081PRedw==
  resetPasswordWithin: +nQDcTY4ulnVx9/Vl6fiaQ==--MX7lgsh65x0gkGWJGr6HZw==
  maximumRetries: ul9dueLqsTsLIWyuhp1GvA==--ueEHaeTE4WrMxiLR5Z/l5Q==
  unlockIn: 3kZebZMLjDUxL5A3y49QAA==--3Pulfxjbdn12P9R3aL2BCA==
  passwordRegex: zhEnf9gHUt46Q351F6YgEBPVAwoO5443wtH9ZrT0tvpwKz5HQ/UfYbQYVz1vawl86SsdtzHWHXeW/nGqbtJ5WUk8wTZqCiIvrpTHYslgN4g=--9Ox/c181l5jCFAaW37Y6kQ==
  confirmationEmail: Nyd1A5NH+RVuSUB4NGXrvQ==--KiK6Y+wwxsCitrkk3Ag4+w==


