
jwt:
  access_token_secret: 6ZeXXu0Nuf3qD6SSJ5jdD0lKvBuCnesMnZFc/RUu4JM=--ZqPHDIL7tjxItSKKKAHI9Q==
  refresh_token_secret: oLRfwerTtocLWn8J9eJUZlV8l7/GEgt/16S49dgCgRQ=--5DG9/O+VTYlsD7V1jL31Hg==

swagger:
  username: fwZ9hD/zJrBnRpGoVUYpk7lYt+fNQp1+U86m0mq+liM=--Itv4WZq1wfbRy2ens+jcow==
  password: rCQGtc3neToZtAIdyHYOpndOD9I6QwR83u0TYibbQZw=--lorcjUUNxsqK6+01h7BpLA==

database:
  name: Jg25YlNS+0HTjAU7XQ9nbQ==--PJ4Ppt3tXYbZShGhLlaqJg==
  host: /Kwiyb5pF7xO6mU9cKDhIw==--6CvOu2l8yCW4Q1R+3cFssw==
  username: mCHdEJr559wCDU7oOhBHcg==--lniu9+yU2oUiLv5cBNmRRA==
  password: 4YPothTxMZsELdFyu/RApg==--ztgQwSu3l9qVmOAtYGc9RA==
  port: vzqyyyhzFzS9I/hpXUE6Zg==--PJzH4hzzUU9eBo/8S2mIZg==

emailLogin:
  tables: RvMe1KqTw4tgZ3ef5ySiapbfEVg14rK6SR2IKKdSeLk=--O5/9RuvgpWMY1RFK7VAFNA==
  passwordMinLength: UAy4y7EKHF5GOn+YhaPOMg==--7/fuq8ldVJKyF9IfbVfNHQ==
  rememberFor: zJuBpi+Ju2Oi5IpBbgD5FA==--HoHIpymXUoH6T8z/s44+oA==
  resetPasswordWithin: vrPU1Ff916xHzUnh7lY6rA==--SR6L5/mxOk4IyQSWY1ZtHw==
  maximumRetries: 9WLvCouACl4WfRohmBB1XA==--ngomBbaVeL8UK8TztseeTg==
  unlockIn: IdaXqYZlBYxY0YjFwHMZuw==--e4eEoUsSGOrwW7D27N3lEw==
  passwordRegex: uxDL/dllcmJpANafJNQsml8W4f+JmdObwQWFZeLwRxB4q/QmSiz5RIJA46aB1Qe/vghj27BkJ9nGcY2wTMmamT2BOB9IUkVxBOz3J+uOjm0=--h6yG2hiaFCKRnZCYRrj5Lw==
  confirmationEmail: C4jYbHX3Q2jr3KYTV0Tl0w==--puEpEBwCKDf+UumNmBfFiA==

twilioLogin:
  userTables: TwmV5QG9M+BqPQm6wbLR5EPOw5mWsOfa5SvDk7bXDQw=--QgAkNu0cT9ZFWqJnQVm7wg==
  serviceId: cx03DEIbdHIdG4gHZdiwadBN3yjNf5gl88p0ZZQtQmrDquX9Ci4n45JhANQPTEnf--7OKfjd4u2ygn3u7rHcRR6A==
  sid: ut4hIjOtyUFRPNaEqK/4rHqhtpEtVsDdMaiNWNV6+0yYpKWBvxrmKu5FvLNzhQU/--wLfoodrxFGQdD1jWhryZuw==
  token: rjQhttnFPH5OptnXgqatyzKPQMiS1V9yUmIaSyGwAKJZQ8F0RlNhfQ/3+24vLW52--BPMyQegOm9Q6v6L9XWg2ZQ==


