
jwt:
  access_token_secret: mk4Q24FH3AcM7bSHx/NqzLEh6r0Y62BFv5oxfv9nLp8=--UriiwT2n1/ToomORcNBkUA==
  refresh_token_secret: CLPKgyTzq5l3R3dFzrH/zmo6N6jy7flYiwtO6eLCq80=--zv7SWi+pSZhkE5gVGDcgDg==

swagger:
  username: qmCPXVAS6tTJmylI5pLz1G9SfmjJcDMqZx7GV9VEf5c=--QhrHHkFmhQ/mXHgAqGp8rA==
  password: jUNc015K02esG1heix0irPwivPg/gD1t6lJA5zALfMc=--xeTxt6HFDUJ8JwdzVKYITA==

database:
  name: o1bLtZZnhfw5A/lZYthZ3gLt1qdHjT4JhNUaBHzOqMucum6Y9wIyY0tLCWZ3vMWx--b5VYNyFr3ZwCXIbNunvsHw==
  host: ZtdRHohuhsezAJNEAH50/g==--+hGs/g7hANbG6NoZA1uiew==
  username: qqVfRLoRu1nwsXXtYjYosA==--1sxYew+vyWDQudY0yA4Zcw==
  password: Vz2Kg5DTK2eqR1NFr+pkPQ==--MlSKYseSNTwqLcy8MRCe8g==
  port: sn9ARV47oJUgVW1wwNoMqg==--zfLssIrs6C63yDLF1k/Xew==

emailLogin:
  tables: QzL22hcu6LirkZBITk1Rmg==--sMuQGUDOOF6h2RYMoGORpg==
  passwordMinLength: kiPi15GYU/xm89w5hyOhhg==--RqlqkShE93CRb5QwFKLagw==
  rememberFor: UNZuBslewCGVhOZJU0Ab3w==--ql7N10/fyQo3NbS7PsUlNA==
  resetPasswordWithin: gOChpp6g2sIYHxHM1u6b7Q==--5hCII5hL61ZXTD1oMpx/7Q==
  maximumRetries: RFAmLNVU/cTf12CJ4cfPTw==--yijj9690BjVphRK4JmbgRg==
  unlockIn: UoP9M6C+uxRSCnKyr5HkMQ==--CW97e5fP5OjcmKVkclSBsw==
  passwordRegex: T1cxXN2OfXEwh3SyzXDTCbZZiIdhtp4cOqrs35CVoYXRgvDUcrPE7V6N4bcz5Jt5+bQ1DuP3sTMQBeGLn6v2t5HxV3fYUpwX50hlpesYCUU=--8zyVb4pbpzrOwmuRDvDNOw==
  confirmationEmail: jmtpQF+zQ0vbrtX5mOyXOA==--bUdR8gp8Zl+72ijpbCZpBg==


