
jwt:
  access_token_secret: IaKtISsx3ipeJ6S8thU4U+hDPB5wlx9vptN3US5278w=--Gsy3BqOq1xURtFbRq6eZ/w==
  refresh_token_secret: uPPs7X3T+yBq7BTOkT1Z+3ZVdmQJ/qO8rvsBU2CEG+M=--t+ogF09iWf/FDqKIUxtUtw==

swagger:
  username: US60U/CLD4W3aCqldBmZe/iajpOtkEg0xYoJwc7c+UE=--W8jGxlkxYLZEMoEEspc0LQ==
  password: qEdl+v6AguMQYNqiqDZO4Qi4YI8UvqGx+e13NT47qp8=--guFcUVpOr11wF3Gcqp9bSQ==

database:
  name: /i1syVkUZB5z5/GH07UOMbytthK+DUbKuAG0fvxe470=--l8q76IgXedpSPMmTpM9a4g==
  host: ZnaGMlvmCgaIkxgGWHY0EA==--z0kRlzZeelzVLEZnO9itAA==
  username: 4HPthQ9W+627Ic1tgZkQ0Q==--Oq3nLbjPTe9CQzSAz41Ejw==
  password: 7pIDE9EL66nbAvsSonfVKA==--MEh/wV3U0E4TPRyOozHBVw==
  port: vg4kaH8a8KtyY4ARJ2kbmQ==--tQY4Ta+sel5I7UzFFBRfaw==

emailLogin:
  tables: 6c9LY4vfitKMJAn4YoAXOQ==--cuMFWNWVH/Iu2se4HAjG5A==
  passwordMinLength: gesrAyaE809i1vFpALmSxA==--zPdvLyaxnB8uPQJjgBXLpg==
  rememberFor: CyoUsKeEucY+lUSI/RKTBw==--cPNH4utR7SOMEZkLuAbNJA==
  resetPasswordWithin: aKQOcvisZQ4tTxtx1txWfw==--fAA64gQQEJmW5aEsUxSn0w==
  maximumRetries: nEVxAUioV44vmNNjMSQ67g==--Tzv2CQ46MAIgnLVzSoMVJg==
  unlockIn: W6o19amDHVKkXZGAMaPQ7A==--gFTMQE5U4YP6b2CVeWL8Cg==
  passwordRegex: FnN2IAVlTkG50gE9SEmzBKNELZVka+8kcTd6LZBp3xg6qD/Lms+p+4XvVW9JC5NHJLAqTCfp2kTLPhAFnPoBuq8zPawaaWhELRNRBzS0lYs=--xGW52C8oQfQkiBVgac0iUg==
  confirmationEmail: ysVzgUeRw43x/KQt0aTo8g==--eUchO+lH9v1NlOez29Zrfg==


