
jwt:
  access_token_secret: slPD3aqHCcP/adpbjYLkfVCqSKCBFcv3N3pMiv/+Q7o=--E0rPPCZgCmIqTb0B5GKhOQ==
  refresh_token_secret: 1HMFLDpzZYtzKIp13dskSX0DGycOvDQdso/PIWhK0HY=--dQr7oyK15D54eT8jIhkeBg==

swagger:
  username: k6BdPNZ0AoRkR1WXzYiLaQIINGKM7+rPTS3kFn/XpVY=--StiEfhyzIBZshb19cpXSag==
  password: BpDp+X46vP/+PUQdk9KLO9txEnxIawXWs/0ygdRistg=--Vq166WF4bCJP6uriq9U2Sw==

database:
  name: JURQNRxkXKTYzVVBFZDMeQ==--Dm3gePSw6vjOwMRyYC8kHA==
  host: hwZPOs+vbWa20d1FVJ7M7Q==--Prkm/TUOBskTDqhQ0RDFxw==
  username: jgno79KKNNa6tOXQ/G+OAg==--ImCtD1e1JIP0C9j1Z1JYcA==
  password: Nsj+oHAXGF9WkaQXKJ6enA==--WT77zbNObP7/xSk6qi3x3A==
  port: D1O/WDox7FRS/zu3T5yfcA==--kqoRbBqO7oMmW3h0OI3eZg==

basicAuth:
  username: duDSngRH60RqRcOT5LgKJpT4bnP9/MQjiBGFHhuWTV0jq7Q5GmpXH2iy6qIrIfny--T27mEXo70jH3N874jg/UAQ==
  password: lZg6/153B/qA5EZSt8m1WT0t5roylvWfJh2faFv4T1pdDV5h126K8WdNTbI7DccF--11z336RYDO+9tWHojYjkmw==

emailLogin:
  tables: PT+bYEEVY3jQSHb0drqZJq5UrbXBW6JKxbCv1hjxdT4=--KKL1cPnk6foUQH7+VXUZjg==
  passwordMinLength: YBkjG+6xLrVEnb76ufWR7A==--7uhXTX4weQZX8J1pefeD5w==
  rememberFor: /suMedF8Lzpq61CM3RN96Q==--q6h6FImY+xRnTPDEKg/LyA==
  resetPasswordWithin: ectyNoODFPmJMz/jCRx5TA==--G60tt/kmgJFZktdLn8/Dcw==
  maximumRetries: Pxi5JVTr3R+WX+gWyjH06g==--zYeIzL146AiurMBT+EpjBw==
  unlockIn: bMoc6h92nMS9tAIO8nEyoQ==--jARVwZ0WFd7OnOToQKhuHg==
  passwordRegex: jCKQEVIoiE4OUhej/NHhQmnWF9bLDKhxqbhmxtkT7hF1tXsmx+5fuC7m//AKNXzSls5M7CUvFb8Ocss2AiwiEdB0Vgk2oZ9BqzJItVzS2ms=--nBAy9ho6dRBSrTDmeOYxXw==
  confirmationEmail: KcFhn2i56B1PhkwEOqThlQ==--SwiZW0qeQPRc8RKa8cF+XA==

twilioLogin:
  userTables: FBeSqcK+u8719hB6yeQUKROpdCrj2OFB/t6FLhHpwWk=--8M0UdkQp9NRvmW6lzpaVlQ==
  serviceId: mdLvjYZoMnNiqdwiagqbL2TqYGhsMB/T8QYx6D0ITYtkR2elYXgsPm6crkXqxhuk--yQOdFE+3T7qZodDTwmHDRg==
  sid: u81aDhk2OsONaX34VLd0x6cKY3LtDtfGmkmud2P3g0Z1LWJ6+/ClKMzby5fomy76--D5LJS/jxAyLTv+0MDlSVpg==
  token: I506KGRZV8sUmD+ufreLfzF0bYOU7Ig2tVMbONOqv5Teh17nBUZoPY+B5brF+ND3--GGrUhvOLjKFhT9AMPuA8EQ==


