
jwt:
  access_token_secret: qmX3QuMfdU3XRcO8HsBtUILaFzA62Z74kbGAjBYLmYE=--bLiV1zLsdU/556c+3r5/zw==
  refresh_token_secret: PItDuLwF+mhDT7oL0Wo5cbWCzCAK+RCw7z9NEo9QpyQ=--0/eBYcKhBEImV3zIrQMZgQ==

swagger:
  username: 15UEsVrWbSp5FWjNp1mojcW1cE8aKnl9RW2YX8Z0Ogs=--pImlnoX8kvAymepRlSx2bA==
  password: GtU2AFxP3YrzzbvtdhqjUAAk55RGjkoeqiFynszXf2w=--W6uMT1zfRvwX0nAD2OCNqg==

database:
  name: X1hsFO6T60qMYIj70yAJEEDXrsJsEFMqBXfv92j1aiACtMjJZFgu+WLd/H7tW5u3--p7uYDvleRysgCPQOB0tYjg==
  host: OS8EdcBiwI1oodk8bxKiSA==--ftSTjaGoaufQCFzLRjoW/w==
  username: GGT4waVAZnUeaoTK2SAczw==--8q+1zQ+aGf9L4HHo/+4fHA==
  password: 0i3+WCzn+hxHmOsOw0o8XQ==--i3JPkZsXXK5R8WmdX+Ct8g==
  port: baecExyl32R+TWfVY3nWMw==--qrPA7dbxDGUzO+UMjifGzg==

emailLogin:
  tables: +bfMjUceVSIuyRJJbr1N5w==--8qm6kNeqGumCLkO6pTJY6g==
  passwordMinLength: 8xdWDqaui2MqhVLEIix2uw==--vUtZFIH4+/2YbqgycQkZkQ==
  rememberFor: oF7aWSq87/NTfd7EUH74aQ==--Fw9A5amCV3paXUO88lqj3A==
  resetPasswordWithin: GPzkSaBIlrMN5iIUaPvNnw==--Ewgh7dV1sG94yVkDGtpINg==
  maximumRetries: JQAmWG1vZa0piccgxlP2YA==--VcusXDjB09LJ7BL9bDyJqA==
  unlockIn: WSxJkO/pMPakXPFb9tC07g==--H8FLh3G/a7Tg8x/gdWeiEg==
  passwordRegex: DSsA2Jg4XJhnujgt3TXEJdSw31wvOzeBreg1e/1vyTHpIa9H+iBQjrq71z0s9NpXm2ImC++NG6wCU0orp1a5GvbX4TcOevws5PCheGmDrTo=--+HJjbmEGNDcNujR17xhwwg==
  confirmationEmail: tL/rWNxMDc6zw4u0ddOyUA==--frBoTIDEU96XY8Hv5nx1tA==


